name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to EC2
      env:
        EC2_PUBLIC_DNS: ${{ secrets.EC2_PUBLIC_DNS }}
        DIRECTORY: "flask-server"
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ env.EC2_PUBLIC_DNS }} << 'EOF'
        if [ -d "${DIRECTORY}" ]; then
          echo "Directory exists"
          cd "${DIRECTORY}"
          git pull origin main
          docker-compose down
          docker-compose build
          docker-compose up -d
        else 
          echo "Directory DNI"
          mkdir -p "${DIRECTORY}"
          git clone -b main https://github.com/Resonance-Viz/Backend "${DIRECTORY}"
        fi
        EOF
